### ISSUE TITLE
File name mismatch

### ISSUE THREAD

**Issue by ryanjgill** [necccc/tessel2-fadecandy#3]
I was trying to use this library on a pi zero w and ran in to this issue where the file named `VIdeoFramePacket.js` is being included but the cases don't match.

In `Pixels.js` it has the correct casing `const VideoFramePacket = require('./VideoFramePacket')`

Works on a mac but I think its ignoring case. Seemed silly to do a PR for a file name change.

I'm using this on a clock and its working great!

**Comment by necccc** [comment]
Oh thx! I'll fix it as soon as can.

**Comment by necccc** [comment]
Fixed, released in 2.0.2
