### ISSUE TITLE
how to control each LED strip?

### ISSUE THREAD

**Issue by sctaix** [necccc/tessel2-fadecandy#4]
I connected fadecandy with 8 LED strips.

then how to control each LED strips individually?

Any example?

**Comment by necccc** [comment]
FadeCandy handles the incoming data as it was sent to the full range of LEDs, there is no distinction of LED strips. You can create offsets though.

So if you want to control only the third strip, send in data, that has 
- 2x64 pixels of dark LEDS first
- then 64 pixels of your data on the 3rd strip

**Comment by sctaix** [comment]
I got it!
It means that fadecandy controller send data to every wired LEDs each, so if I want to turn on red color for second line wired 64 LED strip's 3rd, first I have to turn off every LEDs then make offset for.

![image](https://user-images.githubusercontent.com/15074386/42085469-768cdd3e-7bcb-11e8-81e1-1cc6183ec6a5.png)

So, offset should be "66" for second line's 3rd LED, right?


If first LED strip has only 10 LED and second port's LED strip has 20 LED then what is the address for second line 3rd LED? Is it "12"?

**Comment by necccc** [comment]
Yes, corrent!

**Comment by necccc** [comment]
Do not forget that each LED means 3 values in the buffer sent in (R, G, B)

**Comment by sctaix** [comment]
I found this!

"The FadeCandy doesn’t actually know how many LEDs are connected to each connector, so the first LED on Connector 1 is always LED #64 even if you have less than 64 LEDs physically connected to Connector 0."

fadecandy controller is really interesting!!

Thanks a lot!

**Comment by necccc** [comment]
That's true!

So FadeCandy just takes your data, and spreads it over the pins, regardless the number of actually connected LEDS
