### ISSUE TITLE
Adjust LED brightness

### ISSUE THREAD

**Issue by kmegoryc** [necccc/tessel2-fadecandy#7]
Currently there is no way (at least in the documentation) explaining how to dim the LEDs. There are just parameters for r, g, and b. What is the solve for this?

**Comment by necccc** [comment]
True that, dimming RGB values sound weird, this would be more straightforward if we used HSL color definitions, where you can dial down the Luminosity part.

For RGB, it is done by moving the color towards black, the LED's cannot emit "black light" :D so basically they shut down for black colors. 

If you want to dim your LEDs, just calculate your colors in a way, where they animate/transition toward blacks, and you're done!

**Comment by necccc** [comment]
For my clock project, I picked a handy HSL-2-RGB converter lib/algorithm and started to handle my colors in HSL instead of RGB, it was super useful. The fadecandy hardware on the other hand handles RGB so I would not change this within the library

**Comment by kmegoryc** [comment]
Sounds good, thank you!!
